// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/echo.proto

package echo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EchoPayload struct {
	Message              string    `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	SubField             *SubField `protobuf:"bytes,2,opt,name=sub_field,json=subField,proto3" json:"sub_field,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EchoPayload) Reset()         { *m = EchoPayload{} }
func (m *EchoPayload) String() string { return proto.CompactTextString(m) }
func (*EchoPayload) ProtoMessage()    {}
func (*EchoPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_4990368b046ea048, []int{0}
}

func (m *EchoPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoPayload.Unmarshal(m, b)
}
func (m *EchoPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoPayload.Marshal(b, m, deterministic)
}
func (m *EchoPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoPayload.Merge(m, src)
}
func (m *EchoPayload) XXX_Size() int {
	return xxx_messageInfo_EchoPayload.Size(m)
}
func (m *EchoPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoPayload.DiscardUnknown(m)
}

var xxx_messageInfo_EchoPayload proto.InternalMessageInfo

func (m *EchoPayload) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *EchoPayload) GetSubField() *SubField {
	if m != nil {
		return m.SubField
	}
	return nil
}

type SubField struct {
	Time                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SubField) Reset()         { *m = SubField{} }
func (m *SubField) String() string { return proto.CompactTextString(m) }
func (*SubField) ProtoMessage()    {}
func (*SubField) Descriptor() ([]byte, []int) {
	return fileDescriptor_4990368b046ea048, []int{1}
}

func (m *SubField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubField.Unmarshal(m, b)
}
func (m *SubField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubField.Marshal(b, m, deterministic)
}
func (m *SubField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubField.Merge(m, src)
}
func (m *SubField) XXX_Size() int {
	return xxx_messageInfo_SubField.Size(m)
}
func (m *SubField) XXX_DiscardUnknown() {
	xxx_messageInfo_SubField.DiscardUnknown(m)
}

var xxx_messageInfo_SubField proto.InternalMessageInfo

func (m *SubField) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func init() {
	proto.RegisterType((*EchoPayload)(nil), "echo.EchoPayload")
	proto.RegisterType((*SubField)(nil), "echo.SubField")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EchoServiceClient is the client API for EchoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EchoServiceClient interface {
	Echo(ctx context.Context, in *EchoPayload, opts ...grpc.CallOption) (*EchoPayload, error)
}

type echoServiceClient struct {
	cc *grpc.ClientConn
}

func NewEchoServiceClient(cc *grpc.ClientConn) EchoServiceClient {
	return &echoServiceClient{cc}
}

func (c *echoServiceClient) Echo(ctx context.Context, in *EchoPayload, opts ...grpc.CallOption) (*EchoPayload, error) {
	out := new(EchoPayload)
	err := c.cc.Invoke(ctx, "/echo.EchoService/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EchoServiceServer is the server API for EchoService service.
type EchoServiceServer interface {
	Echo(context.Context, *EchoPayload) (*EchoPayload, error)
}

func RegisterEchoServiceServer(s *grpc.Server, srv EchoServiceServer) {
	s.RegisterService(&_EchoService_serviceDesc, srv)
}

func _EchoService_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServiceServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/echo.EchoService/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServiceServer).Echo(ctx, req.(*EchoPayload))
	}
	return interceptor(ctx, in, info, handler)
}

var _EchoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "echo.EchoService",
	HandlerType: (*EchoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _EchoService_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/echo.proto",
}

func init() { proto.RegisterFile("proto/echo.proto", fileDescriptor_4990368b046ea048) }

var fileDescriptor_4990368b046ea048 = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8e, 0xcf, 0x0b, 0x82, 0x30,
	0x14, 0xc7, 0x33, 0xa4, 0x74, 0x42, 0xd4, 0x4e, 0xe2, 0x25, 0xf1, 0x24, 0x04, 0x13, 0xec, 0x16,
	0x74, 0xac, 0x73, 0xa8, 0xf7, 0xd8, 0xf4, 0xf9, 0x03, 0x94, 0x89, 0xd3, 0xa0, 0xff, 0x3e, 0xb6,
	0x35, 0x08, 0xba, 0x7d, 0xdf, 0x87, 0xf7, 0xde, 0xf7, 0x83, 0xf6, 0xe3, 0xc4, 0x67, 0x9e, 0x40,
	0xd9, 0x72, 0xa2, 0x22, 0xb6, 0x65, 0x0e, 0x8e, 0x0d, 0xe7, 0x4d, 0x0f, 0x89, 0x62, 0x6c, 0xa9,
	0x93, 0xb9, 0x1b, 0x40, 0xcc, 0x74, 0x18, 0xf5, 0x5a, 0x54, 0x20, 0xef, 0x56, 0xb6, 0xfc, 0x41,
	0xdf, 0x3d, 0xa7, 0x15, 0xf6, 0xd1, 0x76, 0x00, 0x21, 0x68, 0x03, 0xbe, 0x15, 0x5a, 0xb1, 0x9b,
	0x99, 0x11, 0x9f, 0x90, 0x2b, 0x16, 0xf6, 0xac, 0x3b, 0xe8, 0x2b, 0x7f, 0x1d, 0x5a, 0xb1, 0x97,
	0xee, 0x88, 0xea, 0xcb, 0x17, 0x76, 0x97, 0x34, 0x73, 0xc4, 0x37, 0x45, 0x17, 0xe4, 0x18, 0x8a,
	0x09, 0xb2, 0x65, 0xa9, 0xfa, 0xe7, 0xa5, 0x01, 0xd1, 0x46, 0xc4, 0x18, 0x91, 0xc2, 0x18, 0x65,
	0x6a, 0x2f, 0xbd, 0x6a, 0xa3, 0x1c, 0xa6, 0x57, 0x57, 0x82, 0x3c, 0x97, 0x23, 0x3e, 0xe8, 0xb2,
	0x1f, 0xd9, 0xe0, 0x1f, 0x45, 0x2b, 0xb6, 0x51, 0x8f, 0xcf, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x31, 0x20, 0x11, 0x27, 0x12, 0x01, 0x00, 0x00,
}
